# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args:
            - --maxkb=1024
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
        -   id: black
            args:
                - --line-length=88
-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.3
    hooks:
        -   id: pylint
            name: pylint
            entry: conda run -n era-weather pylint
            args:
                - --max-line-length=88
                - -j 0
                - --verbose
