name: era-weather
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - black
  - gdal
  - geopandas
  - netcdf4
  - pre-commit
  - pip
  - pylint
  - pyproj
  - pyyaml
  - scipy
  - xarray
  - pip:
